services:
  database:
    container_name: cleanit_db
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - cleanit_data:/var/lib/postgresql/data

  api:
    build:
      context: cleanit-backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_DATASOURCE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    ports:
      - '8080:8080'

  frontend:
    build:
      context: cleanit-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api
    depends_on:
      - api
    ports:
      - '3000:80'

volumes:
  cleanit_data: