/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateOrder: typeof import('./components/CreateOrder.vue')['default']
    CustomerSearch: typeof import('./components/CustomerSearch.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    OrderList: typeof import('./components/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
